site_name: Algorithms Sedgewick Solutions
site_description: Solutions to Algorithms Sedgewick Forth Edition.
site_author: Theo Despoudis
site_url: https://techwaydotio.github.io/algorithms-sedgewick/

# Repository
repo_name: Techwaydotio/algorithms-sedgewick
repo_url: https://github.com/Techwaydotio/algorithms-sedgewick

# Copyright
copyright: Built by <a href="http://github.com/techway">Techway</a> &copy; 2020

theme:
  name: minty
  language: en
  highlightjs: true
  hljs_languages:
    - yaml
    - java
nav:
  - Home: index.md

extra_css:
  - css/katex.css
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css

extra_javascript:
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js

markdown_extensions:
  - codehilite
  - toc:
      permalink: false
  - pymdownx.superfences