site_name: Algorithms Sedgewick Solutions
site_description: Solutions to Algorithms Sedgewick Forth Edition.
site_author: Theo Despoudis
site_url: https://techwaydotio.github.io/algorithms-sedgewick/

# Repository
repo_name: Techwaydotio/algorithms-sedgewick
repo_url: https://github.com/Techwaydotio/algorithms-sedgewick

# Copyright
copyright: Built by <a href="http://github.com/Techwaydotio">Techway.io</a> &copy; 2020

theme:
  name: material
  language: en
  highlightjs: true
  hljs_languages:
    - yaml
    - java
  palette:
    primary: red
    accent: blue grey
  font:
    text: Ubuntu
    code: Ubuntu Mono
nav:
  - Preface: index.md
  - 1 Fundamentals:
    - 1.1   Programming Model: Chap01/1.1.md
    - 1.2   Data Abstraction: Chap01/1.2.md
    - 1.3   Bags, Queues, and Stacks: Chap01/1.3.md
    - 1.4   Analysis of Algorithms: Chap01/1.4.md
    - 1.5   Case Study - Union-Find: Chap01/1.5.md

extra_css:
  - css/katex.css
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css

extra_javascript:
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences

plugins:
  - search